#!/usr/bin/env python3
"""Day-2 orchestrator: objective -> LLM (grammar-constrained) -> validated plan
-> FuzzyVM batch.

Usage:
    python3 orchestrator/run_batch.py \\
        --objective "EIP-2929 warm/cold access divergence on nested DELEGATECALL" \\
        --duration 120s

Requires llama-server already running:
    ~/tools/llama.cpp/build/bin/llama-server \\
        -m ~/models/Qwen2.5-Coder-7B-Instruct-Q5_K_M.gguf \\
        --host 127.0.0.1 --port 8080 --n-gpu-layers 999 --ctx-size 8192

The orchestrator does NOT start llama-server itself — keeping the long-lived
model server decoupled from batch invocations avoids cold-load latency between
prompts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import jsonschema
import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "orchestrator" / "plan_schema.json"
GRAMMAR_PATH = REPO_ROOT / "orchestrator" / "plan.gbnf"
FUZZYVM_BIN = REPO_ROOT / "FuzzyVM" / "FuzzyVM"
DEFAULT_OUT_ROOT = REPO_ROOT / "out" / "llm_guided"

sys.path.insert(0, str(REPO_ROOT / "orchestrator"))
try:
    from rag_faiss import retrieve, format_context  # noqa: E402
except (FileNotFoundError, ImportError) as _e:
    sys.stderr.write(f"[orchestrator] FAISS retriever unavailable ({_e}); falling back to rag_stub\n")
    from rag_stub import retrieve, format_context  # noqa: E402


SYSTEM_PROMPT = """You generate JSON "strategy plans" that bias an Ethereum Virtual Machine fuzzer.

A plan tells FuzzyVM which bytecode-building strategies to favor and which opcodes to forbid, so the generated bytecode is more likely to hit a specific consensus-divergence target across EVM clients (geth, nethermind, besu, revm).

Available strategies (pick 5-12 that are relevant; weights 1-100):
- opcodeGenerator:                         random opcode emit
- pushGenerator:                           PUSH1..PUSH32 immediate emission
- mloadGenerator, mstoreGenerator:         memory reads/writes
- sloadGenerator, sstoreGenerator:         persistent storage
- tloadGenerator, tstoreGenerator:         transient storage (EIP-1153)
- memStorageGenerator, hashAndStoreGenerator, returnGenerator, returnDataGenerator, blobhashGenerator
- jumpGenerator, jumpdestGenerator:        control flow
- createCallGenerator, createCallRNGGenerator, randomCallGenerator, callPrecompileGenerator: contract creation / calls

Example plan:
{"plan_id":"PLACEHOLDER_WILL_BE_REPLACED","objective":"EIP-1153 TSTORE/TLOAD visibility on nested DELEGATECALL","fork":"Cancun","strategy_weights":{"tstoreGenerator":80,"tloadGenerator":80,"createCallGenerator":40,"randomCallGenerator":50,"opcodeGenerator":15,"jumpGenerator":10},"constraints":{"banned_opcodes":["SELFDESTRUCT","BLOCKHASH"]},"rationale":"Bias to transient-storage ops inside nested calls; ban SELFDESTRUCT/BLOCKHASH to keep bytecode budget on-objective.","expected_signal":["storage_divergence","gas_divergence"]}

Rules:
- Emit exactly one JSON object. No prose before or after.
- Copy the given objective EXACTLY into `objective` — same characters, no extra spaces, do not edit EIP numbers.
- Pick at least 5 distinct strategies in `strategy_weights`. Do NOT repeat keys.
- Use `constraints.banned_opcodes` for opcodes that would waste bytecode on off-objective behavior.
- `rationale` is one sentence on WHY these weights target the objective.
"""

USER_TEMPLATE = """Target objective: {objective}

Retrieved context:
{context}

Produce a JSON plan that biases FuzzyVM toward hitting this objective on fork {fork}.
Use plan_id="{plan_id_placeholder}" — the orchestrator will overwrite it."""


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text())


def load_grammar() -> str:
    return GRAMMAR_PATH.read_text()


def call_llm(base_url: str, system: str, user: str, grammar: str, max_tokens: int = 1024) -> str:
    # /v1/chat/completions silently drops the `grammar` field; /completion honors it.
    # Qwen2.5 ChatML template assembled manually so we can pin grammar at the native endpoint.
    prompt = (
        f"<|im_start|>system\n{system}<|im_end|>\n"
        f"<|im_start|>user\n{user}<|im_end|>\n"
        f"<|im_start|>assistant\n"
    )
    url = base_url.rstrip("/") + "/completion"
    payload = {
        "prompt": prompt,
        "temperature": 0.6,
        "top_p": 0.9,
        "n_predict": max_tokens,
        "grammar": grammar,
        "stop": ["<|im_end|>", "<|endoftext|>"],
        "cache_prompt": True,
        "dry_multiplier": 0.8,
        "dry_base": 1.75,
        "dry_allowed_length": 2,
        "repeat_penalty": 1.1,
    }
    r = requests.post(url, json=payload, timeout=300)
    r.raise_for_status()
    data = r.json()
    return data["content"]


def canonical_plan_id(plan: dict) -> str:
    clone = {k: v for k, v in plan.items() if k != "plan_id"}
    blob = json.dumps(clone, sort_keys=True, separators=(",", ":")).encode()
    return "plan_" + hashlib.sha256(blob).hexdigest()[:16]


def validate_plan(plan: dict, schema: dict) -> None:
    jsonschema.validate(plan, schema)


def run_fuzzyvm(plan_file: Path, out_dir: Path, threads: int, duration: str | None) -> int:
    if not FUZZYVM_BIN.exists():
        sys.exit(f"FuzzyVM binary not found at {FUZZYVM_BIN} — run `cd FuzzyVM && go build -o FuzzyVM ./cmd/fuzzyvm` first.")
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [str(FUZZYVM_BIN), "run", "--plan", str(plan_file), "--out-dir", str(out_dir), "--threads", str(threads)]
    print(f"[orchestrator] launching: {' '.join(cmd)}", flush=True)
    proc = subprocess.Popen(cmd, cwd=REPO_ROOT / "FuzzyVM")
    if duration:
        secs = _parse_duration(duration)
        t_end = time.monotonic() + secs
        while time.monotonic() < t_end and proc.poll() is None:
            time.sleep(1)
        if proc.poll() is None:
            print(f"[orchestrator] duration {duration} elapsed; terminating", flush=True)
            proc.terminate()
            try:
                proc.wait(timeout=15)
            except subprocess.TimeoutExpired:
                proc.kill()
    else:
        proc.wait()
    return proc.returncode or 0


def _parse_duration(s: str) -> int:
    if s.endswith("s"): return int(s[:-1])
    if s.endswith("m"): return int(s[:-1]) * 60
    if s.endswith("h"): return int(s[:-1]) * 3600
    return int(s)


def dump_bias(plan_file: Path, count: int = 100) -> str:
    cmd = [str(FUZZYVM_BIN), "dump", "--plan", str(plan_file), "--count", str(count)]
    r = subprocess.run(cmd, cwd=REPO_ROOT / "FuzzyVM", capture_output=True, text=True, timeout=120)
    return r.stdout + r.stderr


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--objective", required=True)
    ap.add_argument("--fork", default="Cancun")
    ap.add_argument("--llm-url", default="http://127.0.0.1:8080")
    ap.add_argument("--threads", type=int, default=4)
    ap.add_argument("--duration", default=None, help="e.g. 120s, 5m, 1h; omit for unbounded")
    ap.add_argument("--out-root", default=str(DEFAULT_OUT_ROOT))
    ap.add_argument("--dry-run", action="store_true", help="Emit + validate plan, skip FuzzyVM run")
    ap.add_argument("--verify-bias", action="store_true", help="After run, also `./FuzzyVM dump` to verify bias")
    args = ap.parse_args()

    schema = load_schema()
    grammar = load_grammar()
    ctx = format_context(retrieve(args.objective))

    user_prompt = USER_TEMPLATE.format(
        objective=args.objective, context=ctx, fork=args.fork,
        plan_id_placeholder="PLACEHOLDER_WILL_BE_REPLACED",
    )

    print(f"[orchestrator] calling LLM at {args.llm_url}", flush=True)
    raw = call_llm(args.llm_url, SYSTEM_PROMPT, user_prompt, grammar)

    try:
        plan = json.loads(raw)
    except json.JSONDecodeError as e:
        sys.stderr.write(f"LLM emitted invalid JSON despite grammar: {e}\n--- raw output ---\n{raw}\n")
        return 2

    plan["plan_id"] = canonical_plan_id(plan)

    try:
        validate_plan(plan, schema)
    except jsonschema.ValidationError as e:
        sys.stderr.write(f"Plan failed schema validation: {e.message}\n--- plan ---\n{json.dumps(plan, indent=2)}\n")
        return 3

    batch_dir = Path(args.out_root) / plan["plan_id"]
    batch_dir.mkdir(parents=True, exist_ok=True)
    plan_file = batch_dir / "plan.json"
    plan_file.write_text(json.dumps(plan, indent=2))
    print(f"[orchestrator] plan validated + written: {plan_file}", flush=True)
    print(f"[orchestrator] objective: {plan['objective']}", flush=True)
    print(f"[orchestrator] fork: {plan['fork']}  weights: {len(plan.get('strategy_weights', {}))}  banned: {len(plan.get('constraints', {}).get('banned_opcodes', []))}", flush=True)

    if args.dry_run:
        print("[orchestrator] --dry-run: skipping FuzzyVM launch", flush=True)
        if args.verify_bias:
            print("\n[orchestrator] bias dump:\n" + dump_bias(plan_file))
        return 0

    rc = run_fuzzyvm(plan_file, batch_dir / "out", args.threads, args.duration)
    print(f"[orchestrator] FuzzyVM exited with rc={rc}", flush=True)

    if args.verify_bias:
        print("\n[orchestrator] bias dump:\n" + dump_bias(plan_file))

    return 0


if __name__ == "__main__":
    sys.exit(main())
