#!/usr/bin/env python3
"""Static corpus metrics for a FuzzyVM state-test directory.

Extracts the generated bytecode from each FuzzyVM-*.json, disassembles it,
and aggregates:
  - tests_total        : number of state-test JSONs scanned
  - tests_with_code    : tests whose pre-state has a non-empty account code
  - unique_bytecodes   : distinct bytecode strings (sha256 of hex body)
  - dedup_rate         : unique / total  (lower means more duplicates)
  - opcode_freq        : histogram of opcode names
  - unique_ngrams_n3   : distinct opcode 3-grams
  - unique_ngrams_n5   : distinct opcode 5-grams
  - total_opcodes      : total opcodes across the corpus

Output is a single JSON doc on stdout (and optionally written to --out).

No VM is started. Pure JSON parsing + a static opcode table, so it's cheap
to run alongside the fuzzer without stealing CPU from the fuzz workers.
"""
from __future__ import annotations

import argparse
import glob
import hashlib
import json
import multiprocessing as mp
import os
import sys
import time
from collections import Counter
from pathlib import Path


OPCODES: dict[int, str] = {
    0x00: "STOP", 0x01: "ADD", 0x02: "MUL", 0x03: "SUB", 0x04: "DIV",
    0x05: "SDIV", 0x06: "MOD", 0x07: "SMOD", 0x08: "ADDMOD", 0x09: "MULMOD",
    0x0A: "EXP", 0x0B: "SIGNEXTEND",
    0x10: "LT", 0x11: "GT", 0x12: "SLT", 0x13: "SGT", 0x14: "EQ",
    0x15: "ISZERO", 0x16: "AND", 0x17: "OR", 0x18: "XOR", 0x19: "NOT",
    0x1A: "BYTE", 0x1B: "SHL", 0x1C: "SHR", 0x1D: "SAR",
    0x20: "KECCAK256",
    0x30: "ADDRESS", 0x31: "BALANCE", 0x32: "ORIGIN", 0x33: "CALLER",
    0x34: "CALLVALUE", 0x35: "CALLDATALOAD", 0x36: "CALLDATASIZE",
    0x37: "CALLDATACOPY", 0x38: "CODESIZE", 0x39: "CODECOPY",
    0x3A: "GASPRICE", 0x3B: "EXTCODESIZE", 0x3C: "EXTCODECOPY",
    0x3D: "RETURNDATASIZE", 0x3E: "RETURNDATACOPY", 0x3F: "EXTCODEHASH",
    0x40: "BLOCKHASH", 0x41: "COINBASE", 0x42: "TIMESTAMP", 0x43: "NUMBER",
    0x44: "PREVRANDAO", 0x45: "GASLIMIT", 0x46: "CHAINID",
    0x47: "SELFBALANCE", 0x48: "BASEFEE", 0x49: "BLOBHASH",
    0x4A: "BLOBBASEFEE",
    0x50: "POP", 0x51: "MLOAD", 0x52: "MSTORE", 0x53: "MSTORE8",
    0x54: "SLOAD", 0x55: "SSTORE", 0x56: "JUMP", 0x57: "JUMPI",
    0x58: "PC", 0x59: "MSIZE", 0x5A: "GAS", 0x5B: "JUMPDEST",
    0x5C: "TLOAD", 0x5D: "TSTORE", 0x5E: "MCOPY",
    0x5F: "PUSH0",
    0xA0: "LOG0", 0xA1: "LOG1", 0xA2: "LOG2", 0xA3: "LOG3", 0xA4: "LOG4",
    0xF0: "CREATE", 0xF1: "CALL", 0xF2: "CALLCODE", 0xF3: "RETURN",
    0xF4: "DELEGATECALL", 0xF5: "CREATE2",
    0xFA: "STATICCALL", 0xFD: "REVERT", 0xFE: "INVALID", 0xFF: "SELFDESTRUCT",
}
for i in range(32):
    OPCODES[0x60 + i] = f"PUSH{i+1}"
for i in range(16):
    OPCODES[0x80 + i] = f"DUP{i+1}"
    OPCODES[0x90 + i] = f"SWAP{i+1}"


def disassemble(code_hex: str) -> list[str]:
    """Return the opcode name sequence for an EVM bytecode hex string.
    Unknown bytes become 'UNKNOWN_<hex>'. PUSHn consumes n immediate bytes.
    """
    h = code_hex.lower()
    if h.startswith("0x"):
        h = h[2:]
    try:
        b = bytes.fromhex(h)
    except ValueError:
        return []
    out: list[str] = []
    i, n = 0, len(b)
    while i < n:
        op = b[i]
        name = OPCODES.get(op, f"UNKNOWN_{op:02x}")
        out.append(name)
        if 0x60 <= op <= 0x7F:
            i += 1 + (op - 0x5F)
        else:
            i += 1
    return out


def process_file(path: str) -> dict:
    """Scan one FuzzyVM-*.json. Returns per-file stats for merging."""
    try:
        with open(path, "rb") as f:
            d = json.loads(f.read().decode("utf-8", errors="ignore"))
    except (OSError, ValueError):
        return {"tests": 0, "with_code": 0, "bytecode_hashes": set(),
                "opcode_counts": Counter(), "ngrams3": set(), "ngrams5": set(),
                "total_opcodes": 0}

    tests = 0
    with_code = 0
    bc_hashes: set[str] = set()
    opcounts: Counter = Counter()
    ng3: set[tuple] = set()
    ng5: set[tuple] = set()
    total_ops = 0

    for _, test in d.items():
        tests += 1
        pre = test.get("pre", {})
        codes = [c.get("code", "0x") for c in pre.values()
                 if isinstance(c, dict) and c.get("code") and c.get("code") != "0x"]
        if not codes:
            continue
        with_code += 1
        for hx in codes:
            bc_hashes.add(hashlib.sha256(hx.lower().encode()).hexdigest())
            ops = disassemble(hx)
            total_ops += len(ops)
            opcounts.update(ops)
            if len(ops) >= 3:
                for i in range(len(ops) - 2):
                    ng3.add((ops[i], ops[i+1], ops[i+2]))
            if len(ops) >= 5:
                for i in range(len(ops) - 4):
                    ng5.add((ops[i], ops[i+1], ops[i+2], ops[i+3], ops[i+4]))

    return {"tests": tests, "with_code": with_code,
            "bytecode_hashes": bc_hashes, "opcode_counts": opcounts,
            "ngrams3": ng3, "ngrams5": ng5, "total_opcodes": total_ops}


def merge(dst: dict, src: dict) -> None:
    dst["tests"] += src["tests"]
    dst["with_code"] += src["with_code"]
    dst["bytecode_hashes"] |= src["bytecode_hashes"]
    dst["opcode_counts"].update(src["opcode_counts"])
    dst["ngrams3"] |= src["ngrams3"]
    dst["ngrams5"] |= src["ngrams5"]
    dst["total_opcodes"] += src["total_opcodes"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", help="directory to scan (recursively) for FuzzyVM-*.json")
    ap.add_argument("--workers", type=int, default=4,
                    help="parallel worker processes (default 4; keep low if fuzz is running)")
    ap.add_argument("--out", default=None, help="optional path to write the JSON summary")
    ap.add_argument("--progress", action="store_true", help="print progress every 10k files")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    files = glob.glob(str(root / "**" / "FuzzyVM-*.json"), recursive=True)
    if not files:
        print(f"no FuzzyVM-*.json under {root}", file=sys.stderr)
        return 2
    print(f"scanning {len(files)} files with {args.workers} workers", file=sys.stderr)

    agg = {"tests": 0, "with_code": 0, "bytecode_hashes": set(),
           "opcode_counts": Counter(), "ngrams3": set(), "ngrams5": set(),
           "total_opcodes": 0}

    t0 = time.monotonic()
    done = 0
    with mp.Pool(args.workers) as pool:
        for res in pool.imap_unordered(process_file, files, chunksize=64):
            merge(agg, res)
            done += 1
            if args.progress and done % 10000 == 0:
                dt = time.monotonic() - t0
                rate = done / max(dt, 0.001)
                print(f"  {done}/{len(files)}  {rate:.0f} files/s", file=sys.stderr)
    dt = time.monotonic() - t0

    top_ops = sorted(agg["opcode_counts"].items(), key=lambda kv: -kv[1])[:30]
    unique_bc = len(agg["bytecode_hashes"])
    summary = {
        "root": str(root),
        "tests_total": agg["tests"],
        "tests_with_code": agg["with_code"],
        "unique_bytecodes": unique_bc,
        "dedup_rate": round(unique_bc / agg["tests"], 6) if agg["tests"] else 0.0,
        "total_opcodes": agg["total_opcodes"],
        "avg_opcodes_per_test": round(agg["total_opcodes"] / max(agg["with_code"], 1), 2),
        "unique_ngrams_n3": len(agg["ngrams3"]),
        "unique_ngrams_n5": len(agg["ngrams5"]),
        "top_opcodes": [{"op": k, "count": v} for k, v in top_ops],
        "scan_duration_s": round(dt, 2),
        "files_scanned": len(files),
    }
    text = json.dumps(summary, indent=2)
    if args.out:
        Path(args.out).write_text(text)
        print(f"wrote {args.out}", file=sys.stderr)
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
